name: flutter_svg_flare_demo_app
description: Testing svg and flare assets

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.13.0+1
  flare_flutter:
    git:
      url: https://github.com/2d-inc/Flare-Flutter.git
      path: flare_flutter
      ref: 396cd88df7638b86e55b4467364fa2c41cde1558

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/food/
  - assets/flare/
  - assets/interface/
